# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tfdR_beep <- function() {
    .Call(`_tinyfiledialogsR_tfdR_beep`)
}

tfdR_notifyPopup <- function(title, message, icon) {
    .Call(`_tinyfiledialogsR_tfdR_notifyPopup`, title, message, icon)
}

tfdR_messageBox <- function(title, message, dialog, icon, button) {
    .Call(`_tinyfiledialogsR_tfdR_messageBox`, title, message, dialog, icon, button)
}

tfdR_inputBox <- function(title, message, defaultInput) {
    .Call(`_tinyfiledialogsR_tfdR_inputBox`, title, message, defaultInput)
}

tfdR_saveFileDialog <- function(title, defaultPathAndFile, nFilterPatterns, filterPatterns, singleFilterDescription) {
    .Call(`_tinyfiledialogsR_tfdR_saveFileDialog`, title, defaultPathAndFile, nFilterPatterns, filterPatterns, singleFilterDescription)
}

tfdR_openFileDialog <- function(title, defaultPathAndFile, nFilterPatterns, filterPatterns, singleFilterDescription, allowMultipleSelects) {
    .Call(`_tinyfiledialogsR_tfdR_openFileDialog`, title, defaultPathAndFile, nFilterPatterns, filterPatterns, singleFilterDescription, allowMultipleSelects)
}

tfdR_selectFolderDialog <- function(title, defaultPath) {
    .Call(`_tinyfiledialogsR_tfdR_selectFolderDialog`, title, defaultPath)
}

tfdR_colorChooser <- function(title, defaultHexRGB) {
    .Call(`_tinyfiledialogsR_tfdR_colorChooser`, title, defaultHexRGB)
}

tfdR_version <- function() {
    .Call(`_tinyfiledialogsR_tfdR_version`)
}

tfdR_response <- function() {
    .Call(`_tinyfiledialogsR_tfdR_response`)
}

